spring.datasource.url=jdbc:sqlite:stagiaires.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=gestion-stagiaires
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=chienmaitre388@gmail.com
spring.mail.password=vrprliehsiposrhl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
server.port=${PORT:8080}